export enum CalculatorMode {
    COMPUTATION = 1,
    COMPLEX_NUMBER = 2,
    BASE = 3,
    SINGLE_VARIABLE_STATISTICS = 4,
    PAIRED_VARIABLE_STATISTICS = 5,
}

export enum AngleMode {
    DEGREE = "DEGREE",
    RADIAN = "RADIAN",
    GRADIAN = "GRADIAN"
}

export enum NumberDisplayMode {
    FIXED_POINT_0 = "FIXED_POINT_0",
    FIXED_POINT_1 = "FIXED_POINT_1",
    FIXED_POINT_2 = "FIXED_POINT_2",
    FIXED_POINT_3 = "FIXED_POINT_3",
    FIXED_POINT_4 = "FIXED_POINT_4",
    FIXED_POINT_5 = "FIXED_POINT_5",
    FIXED_POINT_6 = "FIXED_POINT_6",
    FIXED_POINT_7 = "FIXED_POINT_7",
    FIXED_POINT_8 = "FIXED_POINT_8",
    FIXED_POINT_9 = "FIXED_POINT_9",
    SCIENTIFIC_NOTATION_0 = "SCIENTIFIC_NOTATION_0",
    SCIENTIFIC_NOTATION_1 = "SCIENTIFIC_NOTATION_1",
    SCIENTIFIC_NOTATION_2 = "SCIENTIFIC_NOTATION_2",
    SCIENTIFIC_NOTATION_3 = "SCIENTIFIC_NOTATION_3",
    SCIENTIFIC_NOTATION_4 = "SCIENTIFIC_NOTATION_4",
    SCIENTIFIC_NOTATION_5 = "SCIENTIFIC_NOTATION_5",
    SCIENTIFIC_NOTATION_6 = "SCIENTIFIC_NOTATION_6",
    SCIENTIFIC_NOTATION_7 = "SCIENTIFIC_NOTATION_7",
    SCIENTIFIC_NOTATION_8 = "SCIENTIFIC_NOTATION_8",
    SCIENTIFIC_NOTATION_9 = "SCIENTIFIC_NOTATION_9",
    NORMAL_NOTATION_1 = "NORMAL_NOTATION_1",
    NORMAL_NOTATION_2 = "NORMAL_NOTATION_2",
}

export enum FrequencyMode {
    ON = "ON",
    OFF = "OFF",
}

export enum NumberBase {
    DECIMAL = "DECIMAL",
    HEXADECIMAL = "HEXADECIMAL",
    BINARY = "BINARY",
    OCTAL = "OCTAL",
}

export enum RegressionMode {
    LINEAR = "LINEAR",
    LOGARITHMIC = "LOGARITHMIC",
    EXPONENTIAL = "EXPONENTIAL",
    POWER = "POWER",
    INVERSE = "INVERSE",
    QUADRATIC = "QUADRATIC",
    AB_EXPONENTIAL = "AB_EXPONENTIAL",
}